version: "3.8"
services:
  cms:
    build:
      context: ./cms/.caddy
      dockerfile: Dockerfile
      args:
        - ENABLE_XDEBUG=false
    volumes:
      - ./cms:/app:delegated
      - ./cms/.caddy/certs:/etc/app/certs
      - ./cms/.caddy/Caddyfile:/etc/Caddyfile
    ports:
      - "8080:80"
      - "8000:443"

  mariadb:
    image: mariadb:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data: